name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025, macos-latest]
        arch: [x86, x64]  
        build_type: [Release]
        
    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM on macOS
      if: runner.os == 'macOS'
      run: |
        brew install llvm

    - name: Configure environment to use Homebrew LLVM
      if: runner.os == 'macOS'
      run: |
        echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        
    - name: Build
      run: |
        python build.py
