name: build editor

on:
  workflow_dispatch
  

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025, macos-latest]
        arch: [x86, x64]  
        build_type: [Debug]
        
    steps:
    - uses: actions/checkout@v4

    - name: Install Python on macOS
      if: runner.os == 'macOS'
      run: |
        brew install python
        brew upgrade python

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt-get install -y build-essential
        
    - name: Build
      run: |
        python build.py editor
